/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_airtheva_assdroid_Native */

#ifndef _Included_net_airtheva_assdroid_Native
#define _Included_net_airtheva_assdroid_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_airtheva_assdroid_Native
 * Method:    HelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_airtheva_assdroid_Native_HelloWorld
  (JNIEnv *, jclass);

/*
 * Class:     net_airtheva_assdroid_Native
 * Method:    LoadScene
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_airtheva_assdroid_Native_LoadScene
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_airtheva_assdroid_Native
 * Method:    DrawScene
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_net_airtheva_assdroid_Native_DrawScene
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     net_airtheva_assdroid_Native
 * Method:    ReleaseScene
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_airtheva_assdroid_Native_ReleaseScene
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
